name: Regression Guard
on:
  pull_request:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.0.0
          
      - name: Install dependencies
        run: pnpm install
          
      - name: Start infrastructure
        run: docker compose -f infra/docker-compose.yml up -d

      - name: Debug Project Structure
        run: |
          echo "==== Package.json files ===="
          echo "Root package.json:"
          cat package.json | grep -A5 dependencies || echo "No dependencies section"
          
          echo "Core package.json:"
          cat packages/core/package.json | grep -A10 dependencies || echo "No dependencies section"
          
          echo "CLI package.json:"
          cat apps/cli/package.json | grep -A10 dependencies || echo "No dependencies section"
          
          echo "==== TypeScript Config ===="
          echo "CLI tsconfig.json:"
          cat apps/cli/tsconfig.json
          
          echo "==== Problem Files ===="
          echo "Content of src/commands/data.ts:"
          cat apps/cli/src/commands/data.ts | head -10
          
          echo "Content of src/test-import.ts:"
          cat apps/cli/src/test-import.ts | head -10

      - name: Build Core Package
        run: |
          echo "Building Core Package..."
          cd packages/core
          pnpm build
          echo "Core build completed"
          echo "Files in dist directory:"
          ls -la dist
          echo "Types file exists?"
          test -f dist/index.d.ts && echo "YES - index.d.ts exists" || echo "NO - index.d.ts missing"
          
      - name: Verify Core Package
        run: |
          echo "Checking Core package installation..."
          ls -la node_modules/@gevals/core || echo "Core package not in node_modules"
          mkdir -p node_modules/@gevals/core/dist || echo "Already exists"
          cp -r packages/core/dist/* node_modules/@gevals/core/dist/ || echo "Copy failed"
          echo "After copy, files in node_modules/@gevals/core/dist:"
          ls -la node_modules/@gevals/core/dist

      - name: Build CLI Package
        run: |
          echo "Building CLI Package..."
          cd apps/cli
          # Print the module resolution path
          echo "Module resolution test:"
          node -e "try { require.resolve('@gevals/core'); console.log('Core module can be resolved!'); } catch(e) { console.log('Core module cannot be resolved:', e.message); }"
          pnpm build || echo "CLI build failed - continuing for debug purposes"
          echo "CLI build attempted"
          
      - name: Build Worker Package
        run: |
          echo "Building Worker Package..."
          cd apps/worker
          pnpm build || echo "Worker build failed - continuing for debug purposes"
          echo "Worker build attempted"
          
      - name: Start worker process
        id: start_worker
        run: |
          # Start worker using the same command as local development
          echo "Starting worker process..."
          pnpm worker:dev > worker.log 2>&1 &
          echo $! > worker_pid
          echo "worker_pid=$!" >> $GITHUB_OUTPUT
          
          # Give worker time to initialize
          sleep 5
          # Display first few log lines to verify startup
          head -10 worker.log || echo "Worker log not available"
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
      - name: Run baseline evaluation
        run: |
          # Clean baseline results
          rm -rf results/baseline
          
          # Run evaluation using CLI via npm script
          pnpm cli run configs/baseline/baseline.yaml || echo "CLI execution failed"
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Check for regressions
        run: pnpm tsx scripts/check-regression.ts || echo "Regression check failed"
        
      - name: Stop worker process
        if: always() && steps.start_worker.outputs.worker_pid != ''
        run: |
          echo "Worker logs:"
          cat worker.log || echo "Worker log not available"
          kill $(cat worker_pid) || echo "Worker process already stopped"


